/**
 * Tiny, dependency-free helpers for reading and rewriting the few SVG attributes
 * that matter for cross-engine rendering. We operate on the raw markup (not a DOM)
 * so a round-trip is byte-stable everywhere except the attributes we deliberately
 * change — important when the file is regenerated by a tool and diffed in git.
 */

export interface TagMatch {
  /** the full opening tag text, e.g. `<svg width="480" ...>` */
  tag: string;
  /** index of `<` in the source */
  start: number;
  /** index just past `>` in the source */
  end: number;
}

/** Find the first `<name ...>` opening tag in the source. */
export function findTag(source: string, name: string): TagMatch | null {
  const re = new RegExp(`<${name}\\b[^>]*>`);
  const m = re.exec(source);
  if (!m) return null;
  return { tag: m[0], start: m.index, end: m.index + m[0].length };
}

/** Read an attribute value from an opening tag, or null. */
export function getAttr(tag: string, name: string): string | null {
  const m = new RegExp(`\\b${name}="([^"]*)"`).exec(tag);
  return m ? m[1] : null;
}

/** Read a numeric attribute (handles "480", "480px", "480.0"), or null. */
export function getNumericAttr(tag: string, name: string): number | null {
  const raw = getAttr(tag, name);
  if (raw == null) return null;
  const m = /^\s*([\d.]+)/.exec(raw);
  return m ? Number(m[1]) : null;
}

export interface SvgInfo {
  root: TagMatch;
  width: number | null;
  height: number | null;
  viewBox: string | null;
  hasViewBox: boolean;
  foreignObject: TagMatch | null;
  foWidth: string | null;
  foHeight: string | null;
}

/** Parse the root `<svg>` and the first `<foreignObject>` (if any). */
export function inspect(source: string): SvgInfo {
  const root = findTag(source, "svg");
  if (!root) throw new Error("no <svg> root element found");
  const viewBox = getAttr(root.tag, "viewBox");
  const fo = findTag(source, "foreignObject");
  return {
    root,
    width: getNumericAttr(root.tag, "width"),
    height: getNumericAttr(root.tag, "height"),
    viewBox,
    hasViewBox: viewBox != null,
    foreignObject: fo,
    foWidth: fo ? getAttr(fo.tag, "width") : null,
    foHeight: fo ? getAttr(fo.tag, "height") : null,
  };
}

/** Replace the first opening tag of `name` using a transform of its text. */
export function replaceTag(
  source: string,
  name: string,
  transform: (tag: string) => string,
): string {
  const t = findTag(source, name);
  if (!t) return source;
  const next = transform(t.tag);
  if (next === t.tag) return source;
  return source.slice(0, t.start) + next + source.slice(t.end);
}